# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Mara"
license = "MIT, GPL"
licenselink = "https://github.com/innerand/mara/blob/master/LICENSE.md"
description = "A simple responsive theme designed for private websites and blogs"
homepage = "http://siteforthistheme.com/"
tags = ["blog", "responsive"]
features = ["blog", "pages", "robots.txt"]
min_version = 0.15

[author]
  name = "Innerlohninger Andreas"
  homepage = "https://nxa.at"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
